#ifndef VRBASE_INPUT_H
#define VRBASE_INPUT_H

#include "GameFramework/Actor.h"
#include "System/predefs.h"
#include "System/EHandle.h"

abstract_class IBaseEntity;
class ABaseController;

extern ABaseController* g_pLeftController;
extern ABaseController* g_pRightController;

//Bitfields offset for button inputs
//These are used by the bitwise math in order to mark/unmark which
//buttons are being pressed.
#define IN_AX				BF(1)
#define IN_BY				BF(2)
#define IN_TRIGGER			BF(3)
#define IN_GRIP				BF(4)
#define IN_MENU				BF(5)

//Describes a specific setting of when a given entity is to be triggered
//by a controller
//These are generated by entities in order to register themeselves with controllers.
struct SEntityInputTriggerRequirement {
	EHANDLE m_ent; //Which entity is to be triggered by this event?
	uint32	m_iButton; //Bitfield - which button are we listening for?
	bool	m_bOnReleased; //Is this triggered when the button is released, instead of pressed?
};

//Each entity will have four of these total - two for each controller, pressed and released.
//In IBaseEntity::PostInit(), every entity will register themselves with their controllers based off of these values.
USTRUCT(BlueprintType)
struct SEntityInputRegistrationButtons {
	GENERATED_USTRUCT_BODY()
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	bool m_AX;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	bool m_BY;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	bool m_TRIGGER;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	bool m_GRIP;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	bool m_MENU;
};

//This has two sets of booleans - one for released, one for pressed.
//Each entity will have two of these, one for each controller.
USTRUCT(BlueprintType)
struct SEntityInputRegistrationParams {
	GENERATED_USTRUCT_BODY()
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	SEntityInputRegistrationButtons m_onPressed;
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = Input)
	SEntityInputRegistrationButtons m_onReleased;
};



#endif VRBASE_INPUT_H
